### Send POST request with json body
POST http://localhost:3000/tictactoe/move
Content-Type: application/json

{
  "board": {
    "B1": "X",
    "B2": "O"
  },
  "move": {
    "field": "A1",
    "value": "X"
  }
}

<> 2022-10-25T095524.200.json

