name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Run build uberjar
      run: lein uberjar
    - name: Docker login to Container-Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io/baloise-codecamp-2022
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build, Tag & Push Dockerfile
      run: |
        docker build -t ghcr.io/baloise-codecamp-2022/clojure-game-api:${{ github.sha }} .
        docker push ghcr.io/baloise-codecamp-2022/clojure-game-api:${{ github.sha }}

    - name: Tag latest for main builds
      if: github.ref == 'refs/heads/main'
      run: |
        docker push ghcr.io/baloise-codecamp-2022/clojure-game-api:latest
